### ISSUE TITLE
fs.fileExistsSync: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sjackman** [h2non/node-bintray#2]
```
❯❯❯ bintray files upload linuxbrew bottles makedepend -n 1.0.5 -f makedepend-1.0.5.x86_64_linux.bottle.tar.gz
/usr/local/lib/node_modules/bintray/lib/common.js:27
      return fs.fileExistsSync(filepath);
                ^
TypeError: undefined is not a function
    at module.exports._Class.fileExists (/usr/local/lib/node_modules/bintray/lib/common.js:27:17)
    at Command.<anonymous> (/usr/local/lib/node_modules/bintray/lib/command/files.js:39:12)
    at Command.listener (/usr/local/lib/node_modules/bintray/node_modules/commander/index.js:287:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/bintray/node_modules/commander/index.js:541:12)
    at Command.parse (/usr/local/lib/node_modules/bintray/node_modules/commander/index.js:427:21)
    at Object.module.exports.parse (/usr/local/lib/node_modules/bintray/lib/cli.js:21:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/bintray/bin/bintray:5:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
❯❯❯ bintray --version
0.1.3
❯❯❯ node --version
v0.12.0
```

**Comment by h2non** [comment]
Fixed. Re-install the package `npm install bintray --force`

Thanks for reporting

**Comment by sjackman** [comment]
Thanks, Tomás.
