### ISSUE TITLE
ReferenceError: fileExists is not defined

### ISSUE THREAD

**Issue by ibrahimennafaa** [h2non/node-bintray#3]
Hi,

I have this issue when calling package-version

```
[...]/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/lib/command/version.js:65
          if (!fileExists(versionfile)) {
               ^
ReferenceError: fileExists is not defined
    at Command.<anonymous> (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/lib/command/version.js:65:16)
    at Command.listener (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/node_modules/commander/index.js:289:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/node_modules/commander/index.js:572:12)
    at Command.parse (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/node_modules/commander/index.js:438:21)
    at Object.module.exports.parse (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/lib/cli.js:21:20)
    at Object.<anonymous> (/Users/ibrahimennafaa/.nvm/versions/node/v0.12.2/lib/node_modules/bintray/bin/bintray:5:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by h2non** [comment]
Oops! Thanks for reporting.

Fixed in `0.1.6`. Just update it! 
```
npm install --force bintray
```

**Comment by ibrahimennafaa** [comment]
Thanks @h2non ! Now I see this: 
```
Package manifest JSON file not found.
```

Where can I have some documentation about that JSON file we need to pass ?

Thanks again

**Comment by h2non** [comment]
You must specify some flags or create a valid JSON with the required values. 

You could try with this:
```
bintray package-version update myorganization myrepository mypackage -n 0.1.0 -c 'My new releases notes' -w 'https://github.com/myorganization/mypackage/README.md
```
